### ISSUE TITLE
Build errors - package not found

### ISSUE THREAD

**Issue by ds8k** [ConnectSDK/Connect-SDK-Cordova-Plugin#16]
Having an issue with getting this integrated into my Ionic application. I got the SDK installed for iOS (pretty simple) but Android is proving to be a challenge. I can't build my project with Cordova as I get a ton of errors about the ConnectSDK files:

```
    [javac] /Users/cameronbates/Developer/NerdyFM/platforms/android/src/com/connectsdk/cordova/ConnectSDKCordova.java:34: error: package com.connectsdk.device does not exist
    [javac] import com.connectsdk.device.ConnectableDevice;
    [javac]                             ^
    [javac] /Users/cameronbates/Developer/NerdyFM/platforms/android/src/com/connectsdk/cordova/ConnectSDKCordova.java:35: error: package com.connectsdk.device does not exist
    [javac] import com.connectsdk.device.SimpleDevicePicker;
    [javac]                             ^
    [javac] /Users/cameronbates/Developer/NerdyFM/platforms/android/src/com/connectsdk/cordova/ConnectSDKCordova.java:36: error: package com.connectsdk.device does not exist
    [javac] import com.connectsdk.device.SimpleDevicePickerListener;
    [javac]                             ^
    [javac] /Users/cameronbates/Developer/NerdyFM/platforms/android/src/com/connectsdk/cordova/ConnectSDKCordova.java:37: error: package com.connectsdk.discovery does not exist
    [javac] import com.connectsdk.discovery.DiscoveryManager;`
```

Looks like I'm the only dummy having this problem. Anyone else willing to help out?

**Comment by frolov-alexey** [comment]
Before compiling cordova project please be sure that you have the latest Android SDK with updated google-play-services, android support repository etc, latest cordova, gradle, all these applications should be accessible from command line.

You can try this simple setup instruction:
 * Create\Download a new cordova project (it can be Connect-SDK-Cordova- API-Sampler)
         - for new empty project use cordova create hello_connect com.example.helloconnect HelloConnect
         - for Sampler use
         git clone https://github.com/ConnectSDK/Connect-SDK-Cordova-API-Sampler.git

 * Go to your project folder
 * Add android platform:
         cordova platform add android 
 * Add ConnectSDK plugin
         cordova plugin add
 https://github.com/ConnectSDK/Connect-SDK-Cordova-Plugin.git#master
 * Add Connect-SDK-Android native library
   - edit platforms/android/build.gradle
    - add a line
    ```
    compile 'com.connectsdk:connect-sdk-android:1.4.4'
    ```
    
    into section dependencies it should look like this:

    ```
    dependencies {
        compile fileTree(dir: 'libs', include: '*.jar')
        // SUB-PROJECT DEPENDENCIES START
        debugCompile project(path: ":CordovaLib", configuration: "debug")
        releaseCompile project(path: ":CordovaLib", configuration: "release")
        // SUB-PROJECT DEPENDENCIES END
        compile 'com.connectsdk:connect-sdk-android:1.4.4'
    }
    ```

 * Build your project
         cordova build android

 * Run your project
         cordova run android

**Comment by ds8k** [comment]
This has been done but compiling still gives me that error. I'm currently running cordova 4.3. Could that be the issue?

**Comment by frolov-alexey** [comment]
No, It works fine with 1.4.3. What errors do you have?

**Comment by ds8k** [comment]
I posted the error above

>/Users/cameronbates/Developer/NerdyFM/platforms/android/src/com/connectsdk/cordova/ConnectSDKCordova.java:34: error: package com.connectsdk.device does not exist

It goes on and one, over 100 errors.

**Comment by frolov-alexey** [comment]
It looks like you don't have ConnectSDK in your dependency list

**Comment by ds8k** [comment]
I've followed the instructions multiple times now. I just did what you listed above, here's my history:

```javascript
cordova create hello_connect com.example.helloconnect HelloConnect
cd hello_connect/
git clone https://github.com/ConnectSDK/Connect-SDK-Cordova-API-Sampler.git
cordova platform add android
cordova plugin add https://github.com/ConnectSDK/Connect-SDK-Cordova-Plugin.git#master
cordova prepare android
```

I then opened the platforms/android folder with Android Studio, added in the line to my build.gradle:
```javascript
dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    // SUB-PROJECT DEPENDENCIES START
    // SUB-PROJECT DEPENDENCIES END
    compile 'com.connectsdk:connect-sdk-android:1.4.4'
}
```

And I get the following error:

```javascript
/Users/cameronbates/Developer/hello_connect/platforms/android/ant-build/AndroidManifest.xml:12: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').
```

Granted this is a different error.

**Comment by ds8k** [comment]
I've now tried both Android Studio methods listed here: http://connectsdk.com/docs/android/setup/

Same result both times with my project.

**Comment by frolov-alexey** [comment]
Did you install `Google Play Services`, `Android Support Repository`, `Android Support Library` in Android SDK Manager?

**Comment by ds8k** [comment]
Yes.

I have all of this in the following branch for my project: https://github.com/ds8k/NerdyFM/tree/feature/connectsdk

**Comment by ds8k** [comment]
Problem fixed. Ultimately I had a plugin that was including another instance of Play Services causing a build error. Fixed and closed.
